name: R_Pi
channels:
        - cbetters
dependencies:
        - python=3.5
        - numpy
        - ipython
        - pytest
        - re
        - pytest-pep8
        - scipy
        - base64
        - flask
        - platform
        - os
        - glob
